# Generated by Django 2.2.7 on 2021-04-06 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Category', models.CharField(choices=[('Statistic', 'Statistic'), ('Mechanics', 'Mechanics'), ('Networks', 'Networks'), ('Electronics', 'Electronics'), ('Machine Learning', 'Machine Learning'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Big Data', 'Big Data')], max_length=50)),
                ('Views', models.IntegerField()),
                ('ISBN', models.IntegerField()),
                ('Author', models.CharField(max_length=50)),
                ('Yop', models.CharField(max_length=50)),
                ('Publisher', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Bookies',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
    ]
