# Generated by Django 2.2.7 on 2021-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Views',
            field=models.CharField(max_length=50),
        ),
    ]
