# Generated by Django 2.2.7 on 2021-04-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210406_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='Description',
        ),
    ]
