# Generated by Django 2.2.7 on 2021-04-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_books_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Category',
            field=models.CharField(choices=[('Statistic', 'Statistic'), ('Mechanics', 'Mechanics'), ('Networks', 'Networks'), ('Electronics', 'Electronics'), ('Machine Learning', 'Machine Learning'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Big Data', 'Big Data')], default='Statistic', max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
