# Generated by Django 2.2.7 on 2021-04-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210406_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratings',
            old_name='is_favorite',
            new_name='ratings',
        ),
    ]
