# Generated by Django 2.2.7 on 2021-04-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210407_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='ratings',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1),
        ),
    ]
