# Generated by Django 2.2.7 on 2021-04-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210407_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='books',
        ),
        migrations.AddField(
            model_name='ratings',
            name='books',
            field=models.ManyToManyField(to='books.Books'),
        ),
    ]
