# Generated by Django 2.2.7 on 2021-04-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20210407_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='books',
        ),
        migrations.AddField(
            model_name='ratings',
            name='books',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Books'),
            preserve_default=False,
        ),
    ]
