# Generated by Django 2.2.7 on 2021-04-07 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210407_1155'),
        ('books', '0013_auto_20210407_1215'),
    ]

    operations = [
    ]
