# Generated by Django 2.2.7 on 2021-04-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_merge_20210407_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='ratings',
        ),
        migrations.AddField(
            model_name='ratings',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_rate', to='books.Books'),
        ),
    ]
