# Generated by Django 2.2.7 on 2021-04-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20210407_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
